#EKF LOCAL (Odom frame)
ekf_filter_node_odom:
  ros__parameters:
    frequency: 30.0
    two_d_mode: true
    publish_tf: true
    map_frame: map
    odom_frame: odom
    base_link_frame: base_link
    world_frame: odom 

    # Odom từ Encoder
    odom0: /odom
    odom0_config: [ true,  true, false,
                   false, false,  true,
                    true, false, false,
                   false, false, false,
                   false, false, false]

    # IMU
    imu0: /imu/data
    imu0_config: [false, false, false,
                  false, false,  true,
                  false, false, false,
                  false, false, false,
                  false, false, false]
    imu0_differential: true

#EKF GLOBAL (Map frame)
ekf_filter_node_map:
  ros__parameters:
    frequency: 30.0
    two_d_mode: true
    publish_tf: true
    map_frame: map
    odom_frame: odom
    base_link_frame: base_link
    world_frame: map

    # Odom Encoder
    odom0: /odom
    odom0_config: [true, true, false,
                   false, false, true,
                   true,  false, false,
                   false, false, false,
                   false, false, false]

    # IMU
    imu0: /imu/data
    imu0_config: [false, false, false,
                  false, false, true,
                  false, false, false,
                  false, false, false,
                  false,  false, false]
    imu0_differential: true
    # GPS (Position X/Y)
    odom1: /odometry/gps
    odom1_config: [false, false, false,
                   false, false, false,
                   false, false, false,
                   false, false, false,
                   false, false, false]

#NAVSAT TRANSFORM (GPS -> Odom)
navsat_transform:
  ros__parameters:
    frequency: 30.0
    magnetic_declination_radians: 0.0 # Cần chỉnh theo địa lý nơi bạn ở (tra Google)
    yaw_offset: 0.0                   # Chỉnh nếu la bàn lắp lệch hướng Bắc
    zero_altitude: true
    broadcast_cartesian_transform: true
    publish_filtered_gps: true
    use_odometry_yaw: false
    wait_for_datum: false